# Use the R plumber base image
FROM rstudio/plumber

# Install required R packages
RUN R -e "install.packages(c('e1071', 'plumber'), repos='https://cloud.r-project.org')"

# Set the working directory
WORKDIR /app

# Copy files to the container
COPY plumber.R /app/plumber.R
COPY svm_model.RData /app/svm_model.RData

# Expose the port the app runs on
EXPOSE 8000

# Run the plumber API
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('plumber.R'); pr$run(host='0.0.0.0', port=8000)"]
